#!/bin/sh

set -e

VAULT_ADDR="${VAULT_ADDR:-http://127.0.0.1:8200}"
VAULT_TOKEN="${VAULT_TOKEN:-root}"
GITHUB_ORG="${GITHUB_ORG:-}"
GITHUB_USER="${GITHUB_USER:-}"

export VAULT_ADDR
export VAULT_TOKEN

OUTPUT_FILE="/tmp/vault-local.generated.properties"

print_section() {
  echo ""
  echo "============================================================"
  echo "$1"
  echo "============================================================"
}

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

print_section "JPostman local Vault setup"
echo "VAULT_ADDR=$VAULT_ADDR"
echo "GITHUB_ORG=${GITHUB_ORG:-<not set; GitHub auth config skipped>}"
echo "GITHUB_USER=${GITHUB_USER:-<not set; GitHub user mapping skipped>}"

print_section "Checking Vault status"
vault status

print_section "Creating developer policy"
vault policy write developer - <<'POLICY'
path "secret/data/*" {
  capabilities = ["create", "update", "read", "delete"]
}

path "secret/metadata/*" {
  capabilities = ["list", "read"]
}
POLICY

print_section "Creating test KV v2 secret"
vault kv put secret/dev/myapp username=testuser password=testpass

print_section "Enabling Userpass auth"
vault auth enable userpass 2>/dev/null || true
vault write auth/userpass/users/testuser password=testpass policies=developer

print_section "Enabling AppRole auth"
vault auth enable approle 2>/dev/null || true
vault write auth/approle/role/my-java-app token_policies=developer token_ttl=1h token_max_ttl=4h

ROLE_ID="$(vault read -field=role_id auth/approle/role/my-java-app/role-id)"
SECRET_ID="$(vault write -field=secret_id -f auth/approle/role/my-java-app/secret-id)"

echo "AppRole Role ID:   $ROLE_ID"
echo "AppRole Secret ID: $SECRET_ID"

print_section "Enabling JWT auth"
vault auth enable jwt 2>/dev/null || true

if ! command_exists openssl; then
  echo "OpenSSL not found. Installing OpenSSL..."
  if command_exists apk; then
    apk add --no-cache openssl
  else
    echo "ERROR: openssl is required, and apk is not available to install it."
    exit 1
  fi
fi

echo "Generating JWT RSA keys..."
rm -f /tmp/jwt-private.pem /tmp/jwt-public.pem

openssl genrsa -out /tmp/jwt-private.pem 2048 >/dev/null 2>&1
openssl rsa -in /tmp/jwt-private.pem -pubout -out /tmp/jwt-public.pem >/dev/null 2>&1

chmod 600 /tmp/jwt-private.pem
chmod 644 /tmp/jwt-public.pem

echo "Configuring JWT auth with generated public key..."
vault write auth/jwt/config jwt_validation_pubkeys=@/tmp/jwt-public.pem

echo "Creating JWT role..."
vault write auth/jwt/role/my-jwt-role role_type=jwt user_claim=sub bound_audiences=my-vault policies=developer ttl=1h

echo "Generating signed JWT..."
NOW="$(date +%s)"

# Local testing only: JWT valid for 1 year
EXP="$((NOW + 31536000))"

b64url() {
  openssl base64 -A | tr '+/' '-_' | tr -d '='
}

HEADER="$(printf '{"alg":"RS256","typ":"JWT"}' | b64url)"
PAYLOAD="$(printf '{"sub":"testuser","aud":"my-vault","iat":%s,"exp":%s}' "$NOW" "$EXP" | b64url)"
SIGNING_INPUT="$HEADER.$PAYLOAD"

SIGNATURE="$(printf '%s' "$SIGNING_INPUT" \
  | openssl dgst -sha256 -sign /tmp/jwt-private.pem -binary \
  | b64url)"

JWT="$SIGNING_INPUT.$SIGNATURE"

JWT_PARTS="$(echo "$JWT" | awk -F. '{print NF}')"
JWT_SIGNATURE_LENGTH="$(echo "$JWT" | awk -F. '{print length($3)}')"

if [ "$JWT_PARTS" != "3" ]; then
  echo "ERROR: Generated JWT is invalid. Expected 3 parts but got $JWT_PARTS."
  exit 1
fi

if [ "$JWT_SIGNATURE_LENGTH" = "0" ]; then
  echo "ERROR: Generated JWT signature is empty."
  exit 1
fi

echo "Testing generated JWT login..."
vault write auth/jwt/login role=my-jwt-role jwt="$JWT" >/dev/null
echo "JWT login test passed."

print_section "Configuring optional GitHub auth"

if [ -n "$GITHUB_ORG" ]; then
  vault auth enable github 2>/dev/null || true
  vault write auth/github/config organization="$GITHUB_ORG"

  if [ -n "$GITHUB_USER" ]; then
    vault write "auth/github/map/users/$GITHUB_USER" value=developer
    echo "GitHub user '$GITHUB_USER' mapped to developer policy."
  else
    echo "GITHUB_USER is not set. GitHub user mapping skipped."
  fi
else
  echo "GITHUB_ORG is not set. GitHub auth configuration skipped."
fi

print_section "Enabling LDAP auth"

vault auth enable ldap 2>/dev/null || true

vault write auth/ldap/config url="ldap://local-openldap:389" userdn="ou=users,dc=jpostman,dc=io" userattr="uid" binddn="cn=admin,dc=jpostman,dc=io" bindpass="adminpass" starttls=false insecure_tls=true

vault write auth/ldap/users/testuser policies=developer

print_section "Writing generated Java test properties"

cat > "$OUTPUT_FILE" <<PROPS
VAULT_ADDR=http://127.0.0.1:8200
VAULT_TOKEN=root

# Default configured auth test
VAULT_AUTH_METHOD=userpass
VAULT_AUTH_PATH=userpass

# Userpass credentials
VAULT_USERPASS_AUTH_PATH=userpass
VAULT_USERNAME=testuser
VAULT_PASSWORD=testpass

# AppRole credentials generated by setup-vault-local.sh
VAULT_APPROLE_AUTH_PATH=approle
VAULT_ROLE_ID=$ROLE_ID
VAULT_SECRET_ID=$SECRET_ID

# JWT credentials generated by setup-vault-local.sh
VAULT_JWT_AUTH_PATH=jwt
VAULT_JWT_ROLE=my-jwt-role
VAULT_JWT=$JWT

# GitHub auth is optional. Create your own GitHub PAT with read:org and set it locally.
VAULT_GITHUB_AUTH_PATH=github
VAULT_GITHUB_TOKEN=

# LDAP credentials
VAULT_LDAP_AUTH_PATH=ldap
VAULT_LDAP_USERNAME=testuser
VAULT_LDAP_PASSWORD=testpass

# KV test values
VAULT_KV_MOUNT=secret
VAULT_SECRET_PATH=dev/myapp

# SSL settings
VAULT_SSL_VERIFY=false
VAULT_SSL_PEM_FILE=/path/to/vault-ca.pem
PROPS

print_section "Done"

echo "Generated Java test properties:"
echo "$OUTPUT_FILE"
echo ""
echo "Copy them back to your project from the host with:"
echo "docker cp local-vault:$OUTPUT_FILE vault-local.properties"
echo ""
echo "GitHub token is not generated by this script."
echo "Create your own GitHub PAT with read:org and set VAULT_GITHUB_TOKEN locally."
