<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.jpostman</groupId>
        <artifactId>jpostman-parent</artifactId>
        <version>1.0.1</version>
    </parent>

    <artifactId>jpostman-vault</artifactId>
    <name>JPostman Vault Integration</name>
    <description>Vault authentication and secret loading helpers for JPostman.</description>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>io.github.jopenlibs</groupId>
            <artifactId>vault-java-driver</artifactId>
            <version>6.2.1</version>
        </dependency>
        <dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>${testng.version}</version>
			<scope>test</scope>
		</dependency>
    </dependencies>
</project>
